name: Manual Build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build_win:
    name: Build package for Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install pip==21.3.1
        pip install qtawesome==1.2.3
        pip install PyQt5==5.15.9
        pip install -r requirements.txt
    - name: Build with pyinstaller for Windows
      run: |
        pyinstaller aas_manager.spec
        xcopy /E /I basyx dist\AAS_Manager\basyx
        cd dist
        7z a AAS_Manager_Win.zip AAS_Manager
    - name: Save Build in artifacts
      uses: actions/upload-artifact@v1
      with:
        name: AAS_Manager_Win
        path: ./dist/AAS_Manager_Win.zip